before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "git submodule init && git submodule --quiet update"
  - "npm install -g bower"
  - "node ./app.js &"
  - "sleep 3"

branches:
  only:
    - master

language: node_js
node_js:
  - 0.8
