nginx-data:
  image: nginx
  volumes:
    - ./client/build:/usr/share/nginx/html

nginx:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  volumes_from:
    - nginx-data
  ports:
    - 8080:80
  links:
    - app

app:
  build: server
  ports:
    - 8081:8001
  volumes:
    - ./server/build:/app
  links:
    - mongo
  environment:
    - SESSION_SECRET=local-secret
    - DEBUG=swagger
    - NODE_ENV=development
  command: bash -c 'npm install -g supervisor && supervisor -e node,js,yaml index.js'

mongo:
  image: mongo
